package by.carkva_gazeta.malitounik

class MenuPesnyData {
    private val pesnyBag = ArrayList<Data>()
    private val pesnyBel = ArrayList<Data>()
    private val pesnyKal = ArrayList<Data>()
    private val pesnyPrasl = ArrayList<Data>()
    private val pesnyTaize = ArrayList<Data>()

    init {
        pesnyBag.add(Data("piesni_bahar_aniol_ad_boha_habryel", "Анёл ад Бога Габрыэль"))
        pesnyBag.add(Data("piesni_bahar_z_dalokaj_facimy", "З далёкай Фацімы"))
        pesnyBag.add(Data("piesni_bahar_lurdauskaja_piesnia", "Люрдаўская песьня"))
        pesnyBag.add(Data("piesni_bahar_mataczka_bozaja", "Матачка Божая"))
        pesnyBag.add(Data("piesni_bahar_maci_bozaja_budslauskaj", "Маці Божая Будслаўская"))
        pesnyBag.add(Data("piesni_bahar_maci_bozaja_u_zyrovicach", "Маці Божая ў Жыровіцах"))
        pesnyBag.add(Data("piesni_bahar_maci_z_facimy", "Маці з Фацімы"))
        pesnyBag.add(Data("piesni_bahar_maci_maja_bozaja", "Маці мая Божая"))
        pesnyBag.add(Data("piesni_bahar_mnie_adnojczy", "Мне аднойчы"))
        pesnyBag.add(Data("piesni_bahar_o_maryja_maci_boha", "О Марыя, Маці Бога (1)"))
        pesnyBag.add(Data("piesni_bahar_o_maryja_maci_boha_2", "О Марыя, Маці Бога (2)"))
        pesnyBag.add(Data("piesni_bahar_pamalisia_maryja", "Памаліся, Марыя"))
        pesnyBag.add(Data("piesni_bahar_da_maci_bozaj_niastomnaj_dapamohi", "Песьня да Маці Божай Нястомнай Дапамогі"))
        pesnyBag.add(Data("piesni_bahar_radujsia_maryja", "Радуйся, Марыя!"))
        pesnyBag.add(Data("piesni_bahar_tabie_maryja_daviaraju_ja", "Табе, Марыя, давяраю я"))
        pesnyBag.add(Data("piesni_bahar_cichaja_pakornaja", "Ціхая, пакорная"))
        pesnyBag.add(Data("piesni_baharodz_zastupnica_duchounaja", "Заступніца духоўная"))
        pesnyBag.add(Data("piesni_bahar_lubic_maryja_mianie", "Любіць Марыя мяне"))
        pesnyBag.add(Data("piesni_bahar_radujsia_dzieva_maci", "Радуйся, Дзева Маці"))
        pesnyBag.add(Data("piesni_bahar_maci_bozaja_u_barunach", "Маці Божая ў Барунах"))
        pesnyBag.add(Data("piesni_bahar_maci_bozaja", "Маці Божая"))
        pesnyBag.add(Data("piesni_bahar_himn_da_imia_maryi", "Гімн да імя Марыі"))
        pesnyBag.add(Data("piesni_bahar_karaleva_supakoju", "Каралева супакою"))

        pesnyBel.add(Data("piesni_belarus_ave_maria_pazniak", "Ave Maria"))
        pesnyBel.add(Data("piesni_belarus_boza_szto_kalis_narody", "Божа, што калісь народы"))
        pesnyBel.add(Data("piesni_belarus_boza_ja_malusia_za_bielarus", "Божа, я малюся за Беларусь"))
        pesnyBel.add(Data("piesni_belarus_vieczna_zyvi_maja_bielarus", "Вечна жывi, мая Беларусь"))
        pesnyBel.add(Data("piesni_belarus_k_tabie_bielarus", "К табе, Беларусь"))
        pesnyBel.add(Data("piesni_belarus_mahutny_boza", "Магутны Божа"))
        pesnyBel.add(Data("piesni_belarus_malusia_za_ciabie_bielarus", "Малюся за цябе, Беларусь"))
        pesnyBel.add(Data("piesni_belarus_malitva_piesniary", "Малітва («Песьняры»)"))
        pesnyBel.add(Data("piesni_belarus_maja_kraina", "Мая краіна"))
        pesnyBel.add(Data("piesni_belarus_my_choczam_boha", "Мы хочам Бога"))
        pesnyBel.add(Data("piesni_belarus_malitva_buraukin", "Малітва (Г. Бураўкін)"))
        pesnyBel.add(Data("piesni_belarus_viarszynia_bielarusi_kryz", "Вяршыня Беларусі – крыж"))

        pesnyKal.add(Data("piesni_kalady_zorka_zazziala_avemaria", "Ave Maria (Зорка зазьзяла)"))
        pesnyKal.add(Data("piesni_kalady_a_szto_heta_za_spievy", "А што гэта за сьпевы"))
        pesnyKal.add(Data("piesni_kalady_a_u_sviecie_nam_navina_byla", "А ў сьвеце нам навіна была"))
        pesnyKal.add(Data("piesni_kalady_a_uczora_z_viaczora", "А ўчора з вячора"))
        pesnyKal.add(Data("piesni_kalady_viasiolych_kaladnych_sviatau", "Вясёлых калядных сьвятаў"))
        pesnyKal.add(Data("piesni_kalady_zazziala_zoraczka_nad_betlejemam", "Зазьзяла зорачка над Бэтлеемам"))
        pesnyKal.add(Data("piesni_kalady_zvon_zvinic", "Звон зьвініць"))
        pesnyKal.add(Data("piesni_kalady_na_szlachu_u_betlejem", "На шляху ў Бэтлеем"))
        pesnyKal.add(Data("piesni_kalady_nieba_i_ziamla", "Неба і зямля"))
        pesnyKal.add(Data("piesni_kalady_nova_radasc_stala", "Нова радасьць стала"))
        pesnyKal.add(Data("piesni_kalady_noczka_cichaja_zarysta", "Ночка цiхая, зарыста"))
        pesnyKal.add(Data("piesni_kalady_noczczu_sviatoj", "Ноччу сьвятой"))
        pesnyKal.add(Data("piesni_kalady_pakazalas_z_nieba_jasnasc", "Паказалась з неба яснасьць"))
        pesnyKal.add(Data("piesni_kalady_pryjdzicie_da_zbaucy", "Прыйдзіце да Збаўцы"))
        pesnyKal.add(Data("piesni_kalady_radasnaja_viestka", "Радасная вестка"))
        pesnyKal.add(Data("piesni_kalady_u_nacznuju_cisz", "У начную ціш"))
        pesnyKal.add(Data("piesni_kalady_uczora_zviaczora_zasviacila_zora", "Учора зьвячора — засьвяціла зора"))
        pesnyKal.add(Data("piesni_kalady_cichaja_nocz_arsiennieva", "Ціхая ноч (пер.Н.Арсеньневай)"))
        pesnyKal.add(Data("piesni_kalady_cichaja_nocz_dziunaja_nocz", "Ціхая ноч, дзіўная ноч"))
        pesnyKal.add(Data("piesni_kalady_cichaja_nocz", "Ціхая ноч"))
        pesnyKal.add(Data("piesni_kalady_pryjdzi_pryjdzi_emanuel_19st", "Прыйдзі, прыйдзі, Эмануэль (ХІХ ст.)"))
        pesnyKal.add(Data("piesni_kalady_pryjdzi_pryjdzi_emanuel", "Прыйдзі, прыйдзі, Эмануэль (XII–ХVIII стст.)"))
        pesnyKal.add(Data("piesni_kalady_pierszaje_rastvo", "Першае Раство"))
        pesnyKal.add(Data("piesni_kalady_zorka_betlejemska", "Зорка Бэтлеемска"))
        pesnyKal.add(Data("piesni_kalady_piesnia_pra_bozaje_naradzennie_boh_prychodzic", "Песьня пра Божае нараджэньне"))
        pesnyKal.add(Data("piesni_kalady_promien_zorki_z_nieba_liusia", "Промень зоркі з неба ліўся"))
        pesnyKal.add(Data("piesni_kalady_u_betlejem", "У Бэтлеем"))
        pesnyKal.add(Data("piesni_kalady_o_zyvatvorny_tvorca_zor", "O, жыватворны Творца зор"))
        pesnyKal.add(Data("piesni_kalady_u_horadzie_cara_davida", "У горадзе цара Давіда"))
        pesnyKal.add(Data("piesni_kalady_zbauca_svietu", "Збаўца сьвету"))
        pesnyKal.add(Data("piesni_kalady_ci_znala_ty_maryja", "Ці знала Ты, Марыя?"))
        pesnyKal.add(Data("piesni_kalady_najpiersz_pra_rastvo_first_noel", "Найперш пра Раство"))
        pesnyKal.add(Data("piesni_kalady_maryja_ci_ty_viedala", "Марыя, ці Ты ведала?"))
        pesnyKal.add(Data("piesni_kalady_pryjdzicie_paklanicca_adeste_fideles", "Прыйдзіце пакланіцца"))
        pesnyKal.add(Data("piesni_kalady_nam_isus_naradziusia", "Нам Ісус нарадзіўся"))
        pesnyKal.add(Data("piesni_kalady_na_rastvo", "На Раство"))
        pesnyKal.add(Data("piesni_kalady_dobry_vieczar", "Добры вечар"))
        pesnyKal.add(Data("piesni_kalady_dzin_dzilin", "Дзінь-дзілінь"))
        pesnyKal.add(Data("piesni_kalady_szto_heta_za_dziva", "Што гэта за дзіва"))

        pesnyPrasl.add(Data("pesny_prasl_0", "Ён паўсюль"))
        pesnyPrasl.add(Data("pesny_prasl_1", "Ісус вызваліў мяне"))
        pesnyPrasl.add(Data("pesny_prasl_2", "Ісус нам дае збаўленьне"))
        pesnyPrasl.add(Data("pesny_prasl_3", "Айцец наш і наш Валадар"))
        pesnyPrasl.add(Data("piesni_prasl_aliluja_chvalecie_z_nieba", "Алілуя! (Хвалеце з неба...)"))
        pesnyPrasl.add(Data("pesny_prasl_5", "Бог блаславіў гэты дзень"))
        pesnyPrasl.add(Data("pesny_prasl_6", "Бог ёсьць любоў"))
        pesnyPrasl.add(Data("pesny_prasl_7", "Богу сьпявай, уся зямля!"))
        pesnyPrasl.add(Data("pesny_prasl_8", "Божа мой"))
        pesnyPrasl.add(Data("pesny_prasl_9", "Браце мой, мы знайшлі Месію"))
        pesnyPrasl.add(Data("pesny_prasl_10", "Весяліся і пляскай у далоні"))
        pesnyPrasl.add(Data("pesny_prasl_11", "Вольная воля"))
        pesnyPrasl.add(Data("pesny_prasl_12", "Вось маё сэрца"))
        pesnyPrasl.add(Data("pesny_prasl_13", "Вядзі мяне, Божа"))
        pesnyPrasl.add(Data("pesny_prasl_14", "Вялікім і цудоўным"))
        pesnyPrasl.add(Data("pesny_prasl_15", "Госпад мой заўсёды па маёй правіцы"))
        pesnyPrasl.add(Data("pesny_prasl_16", "Госпаду дзякуйце, бо добры Ён"))
        pesnyPrasl.add(Data("pesny_prasl_17", "Дай Духа любові"))
        pesnyPrasl.add(Data("pesny_prasl_18", "Дай уславіць Цябе"))
        pesnyPrasl.add(Data("pesny_prasl_19", "Дай, добры Божа"))
        pesnyPrasl.add(Data("pesny_prasl_20", "Дакраніся да маіх вачэй"))
        pesnyPrasl.add(Data("pesny_prasl_21", "Дзякуй за ўсё, што Ты стварыў"))
        pesnyPrasl.add(Data("pesny_prasl_22", "Дзякуй !"))
        pesnyPrasl.add(Data("pesny_prasl_23", "З намі — Пятро і Андрэй"))
        pesnyPrasl.add(Data("pesny_prasl_24", "Знайдзі мяне"))
        pesnyPrasl.add(Data("pesny_prasl_25", "Зоркі далёка"))
        pesnyPrasl.add(Data("pesny_prasl_26", "Кадош (Сьвяты)"))
        pesnyPrasl.add(Data("pesny_prasl_27", "Клічаш ты"))
        pesnyPrasl.add(Data("pesny_prasl_28", "Любоў Твая"))
        pesnyPrasl.add(Data("pesny_prasl_29", "Любіць — гэта ахвяраваць"))
        pesnyPrasl.add(Data("pesny_prasl_30", "Майго жыцьця — мой Бог крыніца"))
        pesnyPrasl.add(Data("pesny_prasl_31", "Маё сэрца"))
        pesnyPrasl.add(Data("pesny_prasl_32", "Маё шчасьце ў Iсуса"))
        pesnyPrasl.add(Data("pesny_prasl_33", "На псалтыры і на арфе"))
        pesnyPrasl.add(Data("pesny_prasl_34", "Настане дзень"))
        pesnyPrasl.add(Data("pesny_prasl_35", "Невычэрпныя ласкі ў Бога"))
        pesnyPrasl.add(Data("pesny_prasl_36", "О, калі б ты паслухаў Мяне"))
        pesnyPrasl.add(Data("pesny_prasl_37", "Ойча мой, к Табе іду"))
        pesnyPrasl.add(Data("pesny_prasl_38", "Ойча, мяне Ты любіш"))
        pesnyPrasl.add(Data("pesny_prasl_39", "Пакліканьне (Човен)"))
        pesnyPrasl.add(Data("pesny_prasl_40", "Пачуй мой кліч, чулы Ойча"))
        pesnyPrasl.add(Data("pesny_prasl_41", "Песьню славы засьпявайма"))
        pesnyPrasl.add(Data("pesny_prasl_42", "Песьня Давіда"))
        pesnyPrasl.add(Data("pesny_prasl_43", "Песьня вячэрняя"))
        pesnyPrasl.add(Data("pesny_prasl_44", "Песьня пілігрыма"))
        pesnyPrasl.add(Data("pesny_prasl_45", "Песьня ранішняя"))
        pesnyPrasl.add(Data("pesny_prasl_46", "Пяцёра пакутнікаў"))
        pesnyPrasl.add(Data("pesny_prasl_47", "Пілігрым"))
        pesnyPrasl.add(Data("pesny_prasl_48", "Руах"))
        pesnyPrasl.add(Data("pesny_prasl_49", "Сьвятло жыцьця"))
        pesnyPrasl.add(Data("pesny_prasl_50", "Сьпявайма добраму Богу"))
        pesnyPrasl.add(Data("pesny_prasl_51", "Сьпявайце Цару"))
        pesnyPrasl.add(Data("pesny_prasl_52", "Так, як імкнецца сарна"))
        pesnyPrasl.add(Data("pesny_prasl_53", "Твая любоў"))
        pesnyPrasl.add(Data("pesny_prasl_54", "Твая прысутнасьць"))
        pesnyPrasl.add(Data("pesny_prasl_55", "Толькі Ісус"))
        pesnyPrasl.add(Data("pesny_prasl_56", "Толькі Бог, толькі ты"))
        pesnyPrasl.add(Data("pesny_prasl_57", "Толькі Бог"))
        pesnyPrasl.add(Data("pesny_prasl_58", "Ты ведаеш сэрца маё"))
        pesnyPrasl.add(Data("pesny_prasl_59", "Ты ведаеш..."))
        pesnyPrasl.add(Data("pesny_prasl_60", "Ты — Госпад мой"))
        pesnyPrasl.add(Data("piesni_prasl_chvala_tabie_vialiki_boh", "Хвала Табе, вялікі Бог"))
        pesnyPrasl.add(Data("pesny_prasl_62", "Хвалім Цябе, Божа!"))
        pesnyPrasl.add(Data("pesny_prasl_63", "Хрыстос уваскрос! (Resucito)"))
        pesnyPrasl.add(Data("pesny_prasl_65", "Шалом алэхем (Мір вам)"))
        pesnyPrasl.add(Data("pesny_prasl_66", "Я люблю Цябе, Ойча міласэрны"))
        pesnyPrasl.add(Data("piesni_prasl_ja_ustanu_rana_kab_spiavac", "Я ўстану рана, каб сьпяваць"))
        pesnyPrasl.add(Data("pesny_prasl_68", "Як гэта хораша й міла"))
        pesnyPrasl.add(Data("piesni_prasl_jamu_za_usio_slava", "Яму за ўсё слава"))
        pesnyPrasl.add(Data("pesny_prasl_70", "Цябе, Бога, хвалім"))
        pesnyPrasl.add(Data("pesny_prasl_71", "Мой Госпад, мой Збаўца"))
        pesnyPrasl.add(Data("pesny_prasl_72", "Крыжовы шлях"))
        pesnyPrasl.add(Data("pesny_prasl_73", "Аднаві маю надзею"))
        pesnyPrasl.add(Data("pesny_prasl_74", "Праслаўляйце Пана Бога"))
        pesnyPrasl.add(Data("pesny_prasl_75", "Радуйся і слаў Яго"))
        pesnyPrasl.add(Data("piesni_prasl_aliluja_leanard_koen_zanna_hauryczenkava", "Алілуя (Я чуў таемны той акорд...)"))
        pesnyPrasl.add(Data("piesni_prasl_bo_lublu", "Бо люблю"))
        pesnyPrasl.add(Data("piesni_prasl_prad_taboju_moj_boh", "Прад табою, мой Бог"))
        pesnyPrasl.add(Data("piesni_prasl_chrystos_uvaskros", "Хрыстос уваскрос"))
        pesnyPrasl.add(Data("piesni_prasl_aliluja_leanard_koen_maryja_trapaszka", "Алілуя (О Божа, памажы нам жыць...)"))
        pesnyPrasl.add(Data("piesni_prasl_aliluja_leanard_koen_eduard_akulin", "Алілуя (Сярод нягод і сумных кроз...)"))
        pesnyPrasl.add(Data("piesni_prasl_pachvala_sviatomu_jazafatu", "Пахвала сьвятому Язафату"))
        pesnyPrasl.add(Data("piesni_prasl_nie_cviki_ciabie_trymali", "Не цьвікі Цябе трымалі, а мой грэх"))
        pesnyPrasl.add(Data("piesni_prasl_kryzu_chrystovy", "Крыжу Хрыстовы"))
        pesnyPrasl.add(Data("piesni_prasl_tvoj_chram", "Твой хpам"))
        pesnyPrasl.add(Data("piesni_prasl_za_usio_tabie_ja_dziakuju", "За ўсё Табе я дзякую"))
        pesnyPrasl.add(Data("piesni_prasl_himn_na_uszanavannie_sviatych", "Гімн на ўшанаваньне сьвятых"))
        pesnyPrasl.add(Data("piesni_prasl_addac_z_lubovi_usio", "Аддаць з любові ўсё"))
        pesnyPrasl.add(Data("piesni_prasl_sionniaszni_dzien", "Сёньняшні дзень"))
        pesnyPrasl.add(Data("piesni_prasl_ci_ty_byu_na_halhofie", "Ці ты быў на Галгофе"))

        pesnyTaize.add(Data("pesny_taize_0", "Magnifikat"))
        pesnyTaize.add(Data("pesny_taize_1", "Ostende nobis"))
        pesnyTaize.add(Data("pesny_taize_2", "Ubi caritas"))
        pesnyTaize.add(Data("pesny_taize_3", "Блаславёны Бог"))
        pesnyTaize.add(Data("pesny_taize_4", "Бог мой, Iсус, сьвяцi нам у цемры"))
        pesnyTaize.add(Data("pesny_taize_5", "Будзь са Мной"))
        pesnyTaize.add(Data("pesny_taize_6", "Дай нам, Божа, моц ласкi Сваёй"))
        pesnyTaize.add(Data("pesny_taize_7", "Дзякуем Табе, Божа наш"))
        pesnyTaize.add(Data("pesny_taize_8", "Дзякуем Табе, Хрысьце"))
        pesnyTaize.add(Data("pesny_taize_9", "Кожны дзень Бог дае мне сiлы"))
        pesnyTaize.add(Data("pesny_taize_10", "Мая душа ў Богу мае спакой"))
        pesnyTaize.add(Data("pesny_taize_11", "О, Iсусе"))
        pesnyTaize.add(Data("pesny_taize_12", "О, Госпадзе мой"))
        pesnyTaize.add(Data("pesny_taize_13", "Прыйдзi, Дух Сьвяты"))
        pesnyTaize.add(Data("pesny_taize_14", "У цемры iдзём"))
        pesnyTaize.add(Data("pesny_taize_15", "У цемры нашых дзён"))
        pesnyTaize.add(Data("pesny_taize_16", "Хай тваё сэрца больш не журыцца"))
    }

    fun getPesnyBag() = pesnyBag

    fun getPesnyBel() = pesnyBel

    fun getPesnyKal() = pesnyKal

    fun getPesnyPrasl() = pesnyPrasl

    fun getPesnyTaize() = pesnyTaize

    fun getPesnyAll(): ArrayList<Data> {
        val result = ArrayList<Data>()
        result.addAll(pesnyBag)
        result.addAll(pesnyBel)
        result.addAll(pesnyKal)
        result.addAll(pesnyPrasl)
        result.addAll(pesnyTaize)
        return result
    }

    data class Data(val resurs: String, val title: String) : Comparable<Data> {
        override fun compareTo(other: Data): Int {
            return this.title.compareTo(other.title, true)
        }
    }
}
