package by.carkva_gazeta.malitounik

class MenuPesnyData {
    private val pesnyBag = ArrayList<Data>()
    private val pesnyBel = ArrayList<Data>()
    private val pesnyKal = ArrayList<Data>()
    private val pesnyPrasl = ArrayList<Data>()
    private val pesnyTaize = ArrayList<Data>()

    init {
        pesnyBag.add(Data("pesny_bag_0", "Анёл ад Бога Габрыэль"))
        pesnyBag.add(Data("pesny_bag_1", "З далёкай Фацімы"))
        pesnyBag.add(Data("pesny_bag_2", "Люрдаўская песьня"))
        pesnyBag.add(Data("pesny_bag_3", "Матачка Божая"))
        pesnyBag.add(Data("pesny_bag_4", "Маці Божая Будслаўская"))
        pesnyBag.add(Data("pesny_bag_5", "Маці Божая ў Жыровіцах"))
        pesnyBag.add(Data("pesny_bag_6", "Маці з Фацімы"))
        pesnyBag.add(Data("pesny_bag_7", "Маці мая Божая"))
        pesnyBag.add(Data("pesny_bag_8", "Мне аднойчы"))
        pesnyBag.add(Data("pesny_bag_9", "О Марыя, Маці Бога (1)"))
        pesnyBag.add(Data("pesny_bag_10", "О Марыя, Маці Бога (2)"))
        pesnyBag.add(Data("pesny_bag_11", "Памаліся, Марыя"))
        pesnyBag.add(Data("pesny_bag_12", "Песьня да Маці Божай Нястомнай Дапамогі"))
        pesnyBag.add(Data("pesny_bag_13", "Радуйся, Марыя!"))
        pesnyBag.add(Data("pesny_bag_14", "Табе, Марыя, давяраю я"))
        pesnyBag.add(Data("pesny_bag_15", "Ціхая, пакорная"))

        pesnyBel.add(Data("pesny_bel_0", "Ave Maria"))
        pesnyBel.add(Data("pesny_bel_1", "Божа, што калісь народы"))
        pesnyBel.add(Data("pesny_bel_2", "Божа, я малюся за Беларусь"))
        pesnyBel.add(Data("pesny_bel_3", "Вечна жывi, мая Беларусь"))
        pesnyBel.add(Data("pesny_bel_4", "К табе, Беларусь"))
        pesnyBel.add(Data("pesny_bel_5", "Магутны Божа"))
        pesnyBel.add(Data("pesny_bel_6", "Малюся за цябе, Беларусь"))
        pesnyBel.add(Data("pesny_bel_7", "Малітва"))
        pesnyBel.add(Data("pesny_bel_8", "Мая краіна"))
        pesnyBel.add(Data("pesny_bel_9", "Мы хочам Бога"))

        pesnyKal.add(Data("pesny_kal_0", "Ave Maria (Зорка зазьзяла)"))
        pesnyKal.add(Data("pesny_kal_1", "А што гэта за сьпевы"))
        pesnyKal.add(Data("pesny_kal_2", "А ў сьвеце нам навіна была"))
        pesnyKal.add(Data("pesny_kal_3", "А ўчора з вячора"))
        pesnyKal.add(Data("pesny_kal_4", "Вясёлых калядных сьвятаў"))
        pesnyKal.add(Data("pesny_kal_5", "Зазьзяла зорачка над Бэтлеемам"))
        pesnyKal.add(Data("pesny_kal_6", "Звон зьвініць"))
        pesnyKal.add(Data("pesny_kal_7", "На шляху ў Бэтлеем"))
        pesnyKal.add(Data("pesny_kal_8", "Неба і зямля"))
        pesnyKal.add(Data("pesny_kal_9", "Нова радасьць стала"))
        pesnyKal.add(Data("pesny_kal_10", "Ночка цiхая, зарыста"))
        pesnyKal.add(Data("pesny_kal_11", "Ноччу сьвятой"))
        pesnyKal.add(Data("pesny_kal_12", "Паказалась з неба яснасьць"))
        pesnyKal.add(Data("piesni_kalady_pryjdzicie_da_zbaucy", "Прыйдзіце да Збаўцы"))
        pesnyKal.add(Data("pesny_kal_14", "Радасная вестка"))
        pesnyKal.add(Data("pesny_kal_15", "У начную ціш"))
        pesnyKal.add(Data("pesny_kal_16", "Учора зьвячора — засьвяціла зора"))
        pesnyKal.add(Data("piesni_kalady_cichaja_nocz_arsiennieva", "Ціхая ноч (пер.Н.Арсеньневай)"))
        pesnyKal.add(Data("piesni_kalady_cichaja_nocz_dziunaja_nocz", "Ціхая ноч, дзіўная ноч"))
        pesnyKal.add(Data("piesni_kalady_cichaja_nocz", "Ціхая ноч"))
        pesnyKal.add(Data("pesny_kal_20", "Прыйдзі, прыйдзі, Эмануэль (ХІХ ст.)"))
        pesnyKal.add(Data("pesny_kal_21", "Прыйдзі, прыйдзі, Эмануэль (XII–ХVIII стст.)"))
        pesnyKal.add(Data("piesni_kalady_pierszaje_rastvo", "Першае Раство"))
        pesnyKal.add(Data("piesni_kalady_zorka_betlejemska", "Зорка Бэтлеемска"))
        pesnyKal.add(Data("piesni_kalady_piesnia_pra_bozaje_naradzennie_boh_prychodzic", "Песьня пра Божае нараджэньне"))
        pesnyKal.add(Data("piesni_kalady_promien_zorki_z_nieba_liusia", "Промень зоркі з неба ліўся"))
        pesnyKal.add(Data("piesni_kalady_u_betlejem", "У Бэтлеем"))

        pesnyPrasl.add(Data("pesny_prasl_0", "Ён паўсюль"))
        pesnyPrasl.add(Data("pesny_prasl_1", "Ісус вызваліў мяне"))
        pesnyPrasl.add(Data("pesny_prasl_2", "Ісус нам дае збаўленьне"))
        pesnyPrasl.add(Data("pesny_prasl_3", "Айцец наш і наш Валадар"))
        pesnyPrasl.add(Data("piesni_prasl_aliluja_chvalecie_z_nieba", "Алілуя! (Хвалеце з неба...)"))
        pesnyPrasl.add(Data("pesny_prasl_5", "Бог блаславіў гэты дзень"))
        pesnyPrasl.add(Data("pesny_prasl_6", "Бог ёсьць любоў"))
        pesnyPrasl.add(Data("pesny_prasl_7", "Богу сьпявай, уся зямля!"))
        pesnyPrasl.add(Data("pesny_prasl_8", "Божа мой"))
        pesnyPrasl.add(Data("pesny_prasl_9", "Браце мой, мы знайшлі Месію"))
        pesnyPrasl.add(Data("pesny_prasl_10", "Весяліся і пляскай у далоні"))
        pesnyPrasl.add(Data("pesny_prasl_11", "Вольная воля"))
        pesnyPrasl.add(Data("pesny_prasl_12", "Вось маё сэрца"))
        pesnyPrasl.add(Data("pesny_prasl_13", "Вядзі мяне, Божа"))
        pesnyPrasl.add(Data("pesny_prasl_14", "Вялікім і цудоўным"))
        pesnyPrasl.add(Data("pesny_prasl_15", "Госпад мой заўсёды па маёй правіцы"))
        pesnyPrasl.add(Data("pesny_prasl_16", "Госпаду дзякуйце, бо добры Ён"))
        pesnyPrasl.add(Data("pesny_prasl_17", "Дай Духа любові"))
        pesnyPrasl.add(Data("pesny_prasl_18", "Дай уславіць Цябе"))
        pesnyPrasl.add(Data("pesny_prasl_19", "Дай, добры Божа"))
        pesnyPrasl.add(Data("pesny_prasl_20", "Дакраніся да маіх вачэй"))
        pesnyPrasl.add(Data("pesny_prasl_21", "Дзякуй за ўсё, што Ты стварыў"))
        pesnyPrasl.add(Data("pesny_prasl_22", "Дзякуй !"))
        pesnyPrasl.add(Data("pesny_prasl_23", "З намі — Пятро і Андрэй"))
        pesnyPrasl.add(Data("pesny_prasl_24", "Знайдзі мяне"))
        pesnyPrasl.add(Data("pesny_prasl_25", "Зоркі далёка"))
        pesnyPrasl.add(Data("pesny_prasl_26", "Кадош (Сьвяты)"))
        pesnyPrasl.add(Data("pesny_prasl_27", "Клічаш ты"))
        pesnyPrasl.add(Data("pesny_prasl_28", "Любоў Твая"))
        pesnyPrasl.add(Data("pesny_prasl_29", "Любіць — гэта ахвяраваць"))
        pesnyPrasl.add(Data("pesny_prasl_30", "Майго жыцьця — мой Бог крыніца"))
        pesnyPrasl.add(Data("pesny_prasl_31", "Маё сэрца"))
        pesnyPrasl.add(Data("pesny_prasl_32", "Маё шчасьце ў Iсуса"))
        pesnyPrasl.add(Data("pesny_prasl_33", "На псалтыры і на арфе"))
        pesnyPrasl.add(Data("pesny_prasl_34", "Настане дзень"))
        pesnyPrasl.add(Data("pesny_prasl_35", "Невычэрпныя ласкі ў Бога"))
        pesnyPrasl.add(Data("pesny_prasl_36", "О, калі б ты паслухаў Мяне"))
        pesnyPrasl.add(Data("pesny_prasl_37", "Ойча мой, к Табе іду"))
        pesnyPrasl.add(Data("pesny_prasl_38", "Ойча, мяне Ты любіш"))
        pesnyPrasl.add(Data("pesny_prasl_39", "Пакліканьне (Човен)"))
        pesnyPrasl.add(Data("pesny_prasl_40", "Пачуй мой кліч, чулы Ойча"))
        pesnyPrasl.add(Data("pesny_prasl_41", "Песьню славы засьпявайма"))
        pesnyPrasl.add(Data("pesny_prasl_42", "Песьня Давіда"))
        pesnyPrasl.add(Data("pesny_prasl_43", "Песьня вячэрняя"))
        pesnyPrasl.add(Data("pesny_prasl_44", "Песьня пілігрыма"))
        pesnyPrasl.add(Data("pesny_prasl_45", "Песьня ранішняя"))
        pesnyPrasl.add(Data("pesny_prasl_46", "Пяцёра пакутнікаў"))
        pesnyPrasl.add(Data("pesny_prasl_47", "Пілігрым"))
        pesnyPrasl.add(Data("pesny_prasl_48", "Руах"))
        pesnyPrasl.add(Data("pesny_prasl_49", "Сьвятло жыцьця"))
        pesnyPrasl.add(Data("pesny_prasl_50", "Сьпявайма добраму Богу"))
        pesnyPrasl.add(Data("pesny_prasl_51", "Сьпявайце Цару"))
        pesnyPrasl.add(Data("pesny_prasl_52", "Так, як імкнецца сарна"))
        pesnyPrasl.add(Data("pesny_prasl_53", "Твая любоў"))
        pesnyPrasl.add(Data("pesny_prasl_54", "Твая прысутнасьць"))
        pesnyPrasl.add(Data("pesny_prasl_55", "Толькі Ісус"))
        pesnyPrasl.add(Data("pesny_prasl_56", "Толькі Бог, толькі ты"))
        pesnyPrasl.add(Data("pesny_prasl_57", "Толькі Бог"))
        pesnyPrasl.add(Data("pesny_prasl_58", "Ты ведаеш сэрца маё"))
        pesnyPrasl.add(Data("pesny_prasl_59", "Ты ведаеш..."))
        pesnyPrasl.add(Data("pesny_prasl_60", "Ты — Госпад мой"))
        pesnyPrasl.add(Data("pesny_prasl_61", "Хвала Табе, вялікі Бог"))
        pesnyPrasl.add(Data("pesny_prasl_62", "Хвалім Цябе, Божа!"))
        pesnyPrasl.add(Data("pesny_prasl_63", "Хрыстос уваскрос! (Resucito)"))
        pesnyPrasl.add(Data("pesny_prasl_64", "Ці ты быў на Галгофе"))
        pesnyPrasl.add(Data("pesny_prasl_65", "Шалом алэхем (Мір вам)"))
        pesnyPrasl.add(Data("pesny_prasl_66", "Я люблю Цябе, Ойча міласэрны"))
        pesnyPrasl.add(Data("piesni_prasl_ja_ustanu_rana_kab_spiavac", "Я ўстану рана, каб сьпяваць"))
        pesnyPrasl.add(Data("pesny_prasl_68", "Як гэта хораша й міла"))
        pesnyPrasl.add(Data("piesni_prasl_jamu_za_usio_slava", "Яму за ўсё слава"))
        pesnyPrasl.add(Data("pesny_prasl_70", "Цябе, Бога, хвалім"))
        pesnyPrasl.add(Data("pesny_prasl_71", "Мой Госпад, мой Збаўца"))
        pesnyPrasl.add(Data("pesny_prasl_72", "Крыжовы шлях"))
        pesnyPrasl.add(Data("pesny_prasl_73", "Аднаві маю надзею"))
        pesnyPrasl.add(Data("pesny_prasl_74", "Праслаўляйце Пана Бога"))
        pesnyPrasl.add(Data("pesny_prasl_75", "Радуйся і слаў Яго"))
        pesnyPrasl.add(Data("piesni_prasl_aliluja", "Алілуя"))

        pesnyTaize.add(Data("pesny_taize_0", "Magnifikat"))
        pesnyTaize.add(Data("pesny_taize_1", "Ostende nobis"))
        pesnyTaize.add(Data("pesny_taize_2", "Ubi caritas"))
        pesnyTaize.add(Data("pesny_taize_3", "Блаславёны Бог"))
        pesnyTaize.add(Data("pesny_taize_4", "Бог мой, Iсус, сьвяцi нам у цемры"))
        pesnyTaize.add(Data("pesny_taize_5", "Будзь са Мной"))
        pesnyTaize.add(Data("pesny_taize_6", "Дай нам, Божа, моц ласкi Сваёй"))
        pesnyTaize.add(Data("pesny_taize_7", "Дзякуем Табе, Божа наш"))
        pesnyTaize.add(Data("pesny_taize_8", "Дзякуем Табе, Хрысьце"))
        pesnyTaize.add(Data("pesny_taize_9", "Кожны дзень Бог дае мне сiлы"))
        pesnyTaize.add(Data("pesny_taize_10", "Мая душа ў Богу мае спакой"))
        pesnyTaize.add(Data("pesny_taize_11", "О, Iсусе"))
        pesnyTaize.add(Data("pesny_taize_12", "О, Госпадзе мой"))
        pesnyTaize.add(Data("pesny_taize_13", "Прыйдзi, Дух Сьвяты"))
        pesnyTaize.add(Data("pesny_taize_14", "У цемры iдзём"))
        pesnyTaize.add(Data("pesny_taize_15", "У цемры нашых дзён"))
        pesnyTaize.add(Data("pesny_taize_16", "Хай тваё сэрца больш не журыцца"))
    }

    fun getPesnyBag() = pesnyBag

    fun getPesnyBel() = pesnyBel

    fun getPesnyKal() = pesnyKal

    fun getPesnyPrasl() = pesnyPrasl

    fun getPesnyTaize() = pesnyTaize

    fun getPesnyAll(): ArrayList<Data> {
        val result = ArrayList<Data>()
        result.addAll(pesnyBag)
        result.addAll(pesnyBel)
        result.addAll(pesnyKal)
        result.addAll(pesnyPrasl)
        result.addAll(pesnyTaize)
        return result
    }

    data class Data(val resurs: String, val title: String) : Comparable<Data> {
        override fun compareTo(other: Data): Int {
            return this.title.compareTo(other.title, true)
        }
    }
}